### ISSUE TITLE
Segfault while running

### ISSUE THREAD

**Issue by temopo** [taviso/loadlibrary#69] opened 2019-07-30 20:47 UTC
Product Version Number          : 1.1.16200.1
root@12345:/loadlibrary/engine# cd ..
root@12345:/loadlibrary# ./mpclient eicar.com
Segmentation fault

**Comment by k4nfr3** [comment] 2019-08-12 13:36
Duplicate of #65

**Comment by taviso** [comment] 2019-08-20 21:46
I Think this is fixed now, thanks for the bug report.

**Closed by taviso** 2019-08-20 21:46 UTC
