### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by blacktop** [taviso/loadlibrary#12] opened 2017-05-25 02:45 UTC
Built using this [Dockerfile](https://github.com/maliceio/malice-windows-defender/blob/master/Dockerfile)

```bash
root@0a074ee74665:/loadlibrary# ./mpclient /malware/EICAR
main(): The map file wasn't found, symbols wont be available
Segmentation fault
```

😢

**Comment by iangcarroll** [comment] 2017-05-25 04:53
Seems to be Docker-specific. Happens with this [minimal Dockerfile](https://gist.github.com/iangcarroll/846e48d6c4d25e583d3957997c9e03c2) as well, even with `--privileged`.

**Comment by taviso** [comment] 2017-05-25 05:02
Hmm, do you have a stacktrace? Also the output of `x/i $pc` and `i r` in gdb.

**Comment by iangcarroll** [comment] 2017-05-25 06:25
```
root@ef0c9b19a570:/loadlibrary# gdb ./mpclient
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
[...]
Reading symbols from ./mpclient...done.
(gdb) run
Starting program: /loadlibrary/mpclient
main(): The map file wasn't found, symbols wont be available

Program received signal SIGSEGV, Segmentation fault.
0xf6e6a71d in ?? ()
(gdb) bt
#0  0xf6e6a71d in ?? ()
#1  0x08049358 in main (argc=1, argv=0xffffde14, envp=0xffffde1c)
    at mpclient.c:187
(gdb) x/i $pc
=> 0xf6e6a71d:	pushl  %fs:0x0
(gdb) i r
eax            0xffffdb4c	-9396
ecx            0x24a3	9379
edx            0x0	0
ebx            0xffffdc20	-9184
esp            0xffffdb38	0xffffdb38
ebp            0xffffdb58	0xffffdb58
esi            0xf69cb118	-157503208
edi            0xffffdcb8	-9032
eip            0xf6e6a71d	0xf6e6a71d
eflags         0x10286	[ PF SF IF RF ]
cs             0x23	35
ss             0x2b	43
ds             0x2b	43
es             0x2b	43
fs             0x0	0
gs             0x63	99
```

**Comment by taviso** [comment] 2017-05-25 12:52
Ah-ha, I think this must be a duplicate of #9 - Current theory is CONFIG_MODIFY_LDT_SYSCALL missing from kernel config?

**Closed by taviso** 2017-05-25 12:52 UTC
Labels: duplicate

**Comment by iangcarroll** [comment] 2017-05-25 16:23
It might be disabled in the Docker for Mac VM; see https://github.com/bioboxes/biobox-minimal-base/issues/2.

**Comment by blacktop** [comment] 2017-05-26 18:02
@iangcarroll where you able to get it working?
