### ISSUE TITLE
Seg fault

### ISSUE THREAD

**Issue by vendforce** [taviso/loadlibrary#65] opened 2019-04-27 21:52 UTC
Can you confirm this error ? 
I cloned a fresh copy into a directory , did make, downloaded definitions. cab extract etc 
No faults during build 

Product Version Number          : 1.1.15900.4 

Segmentation fault (core dumped)

Program received signal SIGSEGV, Segmentation fault.
0xf6873950 in ?? ()

(gdb) add-symbol-file engine/mpengine.dll 0xf6873950
add symbol table from file "engine/mpengine.dll" at
.text_addr = 0xf6873950
Reading symbols from engine/mpengine.dll...(no debugging symbols found)...done.
Program terminated with signal SIGSEGV, Segmentation fault.

**Comment by taviso** [comment] 2019-04-27 22:56
Thanks for letting me know, I can confirm.

```
Program received signal SIGSEGV, Segmentation fault.
0xf68e5950 in ?? ()
1: x/i $pc
=> 0xf68e5950:	mov    eax,fs:0x2c
```

Well, I had to look that up - you don't see code access that TIB offset very often 😮 

Apparently that is a pointer to the TLS array, I had already implemented `TlsGetValue()` and `TlsSetValue()`, but not indirect access via the TIB.

That might take me a day or two to fix, but I'm working on it right now!

**Comment by vendforce** [comment] 2019-05-11 09:47
any word of a fix yet ?

**Comment by LordNoteworthy** [comment] 2019-05-25 04:05
Facing the same issue. while running mpclient (inside docker), get a SIGSEGV

**Comment by k4nfr3** [comment] 2019-07-29 08:46
Hi,
i came accross the same issue, but if I used an older version of the mpengine.dll like for example 1.1.15000.2, then I have no issues. 
But the next one i found 1.1.15900.4 it core dumps.

**Comment by io12** [comment] 2019-08-05 19:35
@k4nfr3 where did you find a copy of v1.1.15000.2? Also @taviso any updates on trying to fix the segfault?

**Comment by k4nfr3** [comment] 2019-08-12 13:35
@io12 : i have used the good old "wayback machine" web site. And if I remember well, it was either the november 2018 last update I think if I can recall properly.

**Comment by io12** [comment] 2019-08-12 13:54
Oh, I also had the idea to use wayback! Thanks!

**Comment by taviso** [comment] 2019-08-19 23:16
OK, there are a few problems,

* It started to use fields I hadn't defined in TEB, easy fix, already committed.
* It started to use initializers from .tls I hadn't handled before - not easy, but no problem. I can fix it soon.
* It has a few more imports, like GetDiskFreeSpaceExW, easy fix.

I'm working on it right now, sorry it took so long to get back to this.

**Comment by taviso** [comment] 2019-08-19 23:17
ETA, tomorrow or the day after (depending on how complicated the .tls code is), I'll post an update here tomorrow.

**Comment by taviso** [comment] 2019-08-20 21:29
Status:

* TLS pointers in TEB now work, very easy.
* I have basic `.tls` parsing working, this is part of [/Zc:threadSafeInit](https://docs.microsoft.com/en-us/cpp/build/reference/zc-threadsafeinit-thread-safe-local-static-initialization?view=vs-2019) support. I just hacked it for now, and allocate a static TLS slot to the template data. If it breaks in future, fixing it won't be too hard now that I understand the problem.
* The new engines try to use [Threadpool](https://docs.microsoft.com/en-us/windows/win32/procthread/thread-pools)s, this is a Vista+ feature, so it looks like Microsoft is decrementing XP support :( I've hacked it for now so it works, but if they depend on more advanced features in future this might be hard work.
* They needed a bunch of new APIs, no problem.

It *basically* works with the latest version now, phew. It needs some more work, but I wanted to get something committed that works because I've ignored this for so long.

Please open new bugs if something doesn't work!

**Closed by taviso** 2019-08-20 21:29 UTC

**Comment by k4nfr3** [comment] 2019-08-21 07:19
@taviso a great thank you for fixing mpclient. After your publication of last week, no wonder to realize how busy you are. Much appreciated
