### ISSUE TITLE
segment fault

### ISSUE THREAD

**Issue by foxrainny** [taviso/loadlibrary#66] opened 2019-05-03 08:37 UTC
Can you confirm this error ?

I tried hard, but i can't...

exiftool mpengine.dll | grep 'Product Version Number'
Product Version Number          : 1.1.15800.1

gdb -q ./mpclient
Reading symbols from ./mpclient...done.
(gdb) r a1.exe

Starting program: /root/pe/loadlibrary-master/mpclient a1.exe
main(): GDB: add-symbol-file engine/mpengine.dll 0xb658d008+0x1000
main(): GDB: shell bash genmapsym.sh 0xb658d008+0x1000 symbols_3224.o < engine/mpengine.map
main(): GDB: add-symbol-file symbols_3224.o 0
Program received signal SIGTRAP, Trace/breakpoint trap.
0x004029d4 in main (argc=2, argv=0xbffff394, envp=0xbffff3a0) at mpclient.c:168
168	            __debugbreak();

(gdb) add-symbol-file engine/mpengine.dll 0xb658d008+0x1000

add symbol table from file "engine/mpengine.dll" at
	.text_addr = 0xb658e008
(y or n) y
Reading symbols from engine/mpengine.dll...(no debugging symbols found)...done.

(gdb) shell bash genmapsym.sh 0xb658d008+0x1000 symbols_3224.o < engine/mpengine.map

(gdb) add-symbol-file symbols_3224.o 0

add symbol table from file "symbols_3224.o" at
	.text_addr = 0x0
(y or n) y
Reading symbols from symbols_3224.o...(no debugging symbols found)...done.

(gdb) p as3_parsemetadata_swf_vars_t

No symbol "as3_parsemetadata_swf_vars_t" in current context.
(gdb) c
Continuing.

Program received signal SIGSEGV, Segmentation fault.
0xb66d738a in ?? ()

a1.exe is a malware sample

1. (no debugging symbols found) < ???
2. No symbol "as3_parsemetadata_swf_vars_t" in current context. <???
3. Program received signal SIGSEGV, Segmentation fault. < ???

**Comment by LordNoteworthy** [comment] 2019-06-04 09:14
Confirm the issue.

**Comment by k4nfr3** [comment] 2019-08-12 13:37
Duplicate of #65

**Comment by taviso** [comment] 2019-08-20 21:48
I think this is fixed now.

**Closed by taviso** 2019-08-20 21:48 UTC
